# Generated by Django 2.0 on 2019-12-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_controllers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllers',
            name='value',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
