# Generated by Django 2.0 on 2019-12-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191224_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controllers',
            new_name='Controller',
        ),
    ]
